[[commands]]
name = "zeek-r"
category = "tests"
command = "zeek -r $1 $2"
help = "zeek -r .pcap <scripts>"


[[commands]]
name = "clean-all"
category = "logs"
command = '''
        rm -rf *.log
        '''
help = "clean all of * logs"


[[commands]]
name = "hardenedlinux-zeek-scripts"
category = "pkgs"
command = "nix -Lv build ./#hardenedlinux-zeek-scripts"
help = "build hardenedlinux-zeek-scripts"
