# nvfetcher.toml
[ja3]
src.git = "https://github.com/salesforce/ja3"
fetch.github = "salesforce/ja3"

[top-dns]
src.git = "https://github.com/corelight/top-dns"
fetch.github = "corelight/top-dns"

[dns-axfr]
src.git = "https://github.com/srozb/dns_axfr"
fetch.github = "srozb/dns_axfr"

[dns-tunnels]
src.git = "https://github.com/hhzzk/dns-tunnels"
fetch.github = "hhzzk/dns-tunnels"

##################
# Public library #
##################
[zeek-known-hosts-with-dns]
src.git = "https://github.com/dopheide-esnet/zeek-known-hosts-with-dns"
fetch.github = "dopheide-esnet/zeek-known-hosts-with-dns"

[zeek-domain-tld]
src.git = "https://github.com/sethhall/domain-tld"
fetch.github = "sethhall/domain-tld"
