# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  CVE-2021-38647 = {
    pname = "CVE-2021-38647";
    version = "5425f651990a7ac3c1462866fe2cdc50aed50565";
    src = fetchgit {
      url = "https://github.com/corelight/CVE-2021-38647";
      rev = "5425f651990a7ac3c1462866fe2cdc50aed50565";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1f4zy5xc2jfb29w924ayq8mpc6j8hfq3h05hwkyxc36mb2mvbcci";
    };
  };
  dns-axfr = {
    pname = "dns-axfr";
    version = "fda4b70516f576a698e0f0f6f1f1e62fc98d258f";
    src = fetchgit {
      url = "https://github.com/srozb/dns_axfr";
      rev = "fda4b70516f576a698e0f0f6f1f1e62fc98d258f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0jf8xi7vb5lfbvrjrlpzzw7rrdcw7ikpw5azykb22h553xw5jjvf";
    };
  };
  dns-tunnels = {
    pname = "dns-tunnels";
    version = "4180a7b2606d11fadb64878d653739a9815ce359";
    src = fetchgit {
      url = "https://github.com/hhzzk/dns-tunnels";
      rev = "4180a7b2606d11fadb64878d653739a9815ce359";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0x5apg1ljlm1zw3p6p8xsilrb5n0z024as73cfhqr6q2xv56s2ic";
    };
  };
  ja3 = {
    pname = "ja3";
    version = "382cd37ea2759bcfc5627d2d7071fe2466833e90";
    src = fetchgit {
      url = "https://github.com/salesforce/ja3";
      rev = "382cd37ea2759bcfc5627d2d7071fe2466833e90";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1wmxpy9ydz7prqny9lp2nhjrwszqbnyvvh4rbcx4015bwpij9fvy";
    };
  };
  scan-NG = {
    pname = "scan-NG";
    version = "80b0c3b9857336e0417c6bc7f92938445b9df48f";
    src = fetchgit {
      url = "https://github.com/initconf/scan-NG";
      rev = "80b0c3b9857336e0417c6bc7f92938445b9df48f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0vjf2b2sf9m2ii7anw512m3md2s7zzfpdpigk13q62jmnir004m6";
    };
  };
  sip-attacks = {
    pname = "sip-attacks";
    version = "1b8c5feb73a732e2ddd8419159f1cbd24c8b9f69";
    src = fetchgit {
      url = "https://github.com/initconf/sip-attacks";
      rev = "1b8c5feb73a732e2ddd8419159f1cbd24c8b9f69";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1n9vdmc8l0vz9wmdy3b866vf0i4i0y43av3al2df4yrf49mjxsrx";
    };
  };
  top-dns = {
    pname = "top-dns";
    version = "d08b1a5665e47ff983debe5a85c0dc8b52aee019";
    src = fetchgit {
      url = "https://github.com/corelight/top-dns";
      rev = "d08b1a5665e47ff983debe5a85c0dc8b52aee019";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "14w6nmjalvh5jxwcd8hh86nlzr448nm6mfr5ny239naflb0p1jv4";
    };
  };
  zeek-domain-tld = {
    pname = "zeek-domain-tld";
    version = "6348921402150ca6571c25c71719c0e1e368f86f";
    src = fetchgit {
      url = "https://github.com/sethhall/domain-tld";
      rev = "6348921402150ca6571c25c71719c0e1e368f86f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "028ilp9pn5d3d94vygsr8y5qxkw0s3a1nzqwdxn3dxy0d7npca2l";
    };
  };
  zeek-known-hosts-with-dns = {
    pname = "zeek-known-hosts-with-dns";
    version = "5ba64d528bdac204e1a09d70070733ff38b1b205";
    src = fetchgit {
      url = "https://github.com/dopheide-esnet/zeek-known-hosts-with-dns";
      rev = "5ba64d528bdac204e1a09d70070733ff38b1b205";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "13n2wjq2kbs0yf06xbja46lb1ws55dy2cc37n1k3fqkj75dscd53";
    };
  };
  zeek-os-package-tracking = {
    pname = "zeek-os-package-tracking";
    version = "5345b12e6ba2cf1990fc5510aa649a6c234b82bb";
    src = fetchgit {
      url = "https://github.com/0xxon/zeek-os-package-tracking";
      rev = "5345b12e6ba2cf1990fc5510aa649a6c234b82bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1nsfnr761z7bhv414pky5lmdh9hwli5030x6l44hnknsisp23amz";
    };
  };
  zeek-sumstats-counttable = {
    pname = "zeek-sumstats-counttable";
    version = "4340348f23b5e807f2f8eae835eb02170efee347";
    src = fetchgit {
      url = "https://github.com/0xxon/zeek-sumstats-counttable";
      rev = "4340348f23b5e807f2f8eae835eb02170efee347";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0ngyjscwzc2j6qqm5myk7fn2s8j8hx82j12dmaxnivpqi6xbkcav";
    };
  };
}
