# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  dns-axfr = {
    pname = "dns-axfr";
    version = "fda4b70516f576a698e0f0f6f1f1e62fc98d258f";
    src = fetchgit {
      url = "https://github.com/srozb/dns_axfr";
      rev = "fda4b70516f576a698e0f0f6f1f1e62fc98d258f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0jf8xi7vb5lfbvrjrlpzzw7rrdcw7ikpw5azykb22h553xw5jjvf";
    };

  };
  dns-tunnels = {
    pname = "dns-tunnels";
    version = "4180a7b2606d11fadb64878d653739a9815ce359";
    src = fetchgit {
      url = "https://github.com/hhzzk/dns-tunnels";
      rev = "4180a7b2606d11fadb64878d653739a9815ce359";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0x5apg1ljlm1zw3p6p8xsilrb5n0z024as73cfhqr6q2xv56s2ic";
    };

  };
  top-dns = {
    pname = "top-dns";
    version = "d08b1a5665e47ff983debe5a85c0dc8b52aee019";
    src = fetchgit {
      url = "https://github.com/corelight/top-dns";
      rev = "d08b1a5665e47ff983debe5a85c0dc8b52aee019";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "14w6nmjalvh5jxwcd8hh86nlzr448nm6mfr5ny239naflb0p1jv4";
    };

  };
}
