#fields indicator_type  meta.url        meta.do_notice
Intel::ADDR http://sednya.info/app/watchdog.exe T
http://92.63.197.153/3.exe T
http://92.63.197.153/2.exe T
http://92.63.197.153/1.exe
http://tangocheats.site/files/miners/x32.exe
http://tangocheats.site/files/miners/x64.exe
http://otech-dz.com/msword.exe
http://91.243.82.85/xxx/updatewin25.exe
http://91.243.82.85/xxx/updatewin15.exe
http://91.243.82.85/xxx/updatewin0.exe
http://91.243.82.85/xxx/55.exe
http://91.243.82.85/xxx/45.exe
http://91.243.82.85/xxx/35.exe
http://91.243.82.85/TRtasdgvgpoidfg87gs7df754ad4asdxzffdfasdfREER/update1.exe
http://92.63.197.153/1.exe
http://92.63.197.153/2.exe
http://92.63.197.153/3.exe
http://pilypas.lt/dainius/wp-admin/css/colors/blue/msg.jpg
http://piksel.as/wp-content/plugins/akismet/_inc/img/msg.jpg
http://pckaruku.com/link/msg.jpg
http://nimrodsson.se/wp-content/themes/sparkling/languages/msg.jpg
http://mojang.com.br/wp-content/themes/twentyseventeen/inc/msg.jpg
http://eigo-t.net/cd/msg.jpg
http://digiserveis.es/wp-content/themes/digiserveis/images/design/link/msg.jpg
http://cdn-07.anonfile.com/KcSc1bu5bb/f9d994b7-1550760594/InstagramChecker2019.exe
http://lollipopnails.com/wp-content/themes/bizworx/js/msg.jpg
http://haglfurniture.vn/templates/dogo/html/com_contact/contact/msg.jpg
http://stories21.com/wp-includes/ID3/msg.jpg
http://brewer-engr.com/templates/jsn_epic_free/ext/k2/msg.jpg
http://v3.viennateng.com/news/wp-admin/css/msg.jpg
http://sgpartneriai.lt/templates/teisininkams3/images/msg.jpg
http://test.mrshears.in/details/msg.jpg
http://suvaforklift.com/js/msg.jpg
http://scopriteistanbul.com/wp-content/themes/italian/javascript/cufon/msg.jpg
http://sarackredi.com/wp-content/themes/webyazilim/css/msg.jpg
http://richmondmovingservice.com/wp-admin/css/colors/blue/msg.jpg
http://proartmusica.com/wp-content/themes/proartmusicatheme/inc/msg.jpg
http://philpaisley.com/wp-content/themes/twentyten/languages/msg.jpg
http://people4u.eu/templates/tem_trentco/html/com_content/archive/msg.jpg
http://meecamera.com/ad/admin/images/flags/msg.jpg
http://matrimony4christians.com/js/msg.jpg
http://markthedates.com/drupal-7.54/msg.jpg
http://gold-cc.com/wp-content/languages/msg.jpg
http://greekonions.gr/templates/school/html/com_content/archive/msg.jpg
http://cinemaxxi.me/wp-includes/ID3/msg.jpg
http://cgiandi.com/wp-content/themes/lowel/vc_templates/msg.jpg
http://all4dl.ir/wp-content/themes/modernfile/images/msg.jpg
http://aioshipping.com/.well-known/acme-challenge/msg.jpg
http://abccomics.com.br/templates/abccomicstheme/css/msg.jpg
http://tmatools.com/cache/mod_mainmenu/msg.jpg
http://185.252.144.58/tin.png
http://185.252.144.58/win.png
http://185.252.144.58/sin.png
http://185.252.144.58/toler.png
http://185.252.144.58/worming.png
http://185.252.144.58/radiance.png
http://185.252.144.58/table.png
http://bullerwelsh.com/templates/templatename/sass/bootstrap/tests/msg.jpg
http://juliecahillphotography.com/wp-content/themes/rebecca/contactpage/msg.jpg
http://computrend.net/wp-content/themes/total/js/msg.jpg
http://brameda.com/wp-content/themes/visia/font/msg.jpg
http://peccapics.com/wp-content/themes/peccadillo/img/carousel/msg.jpg
http://business.driverclub.co/.well-known/pki-validation/msg.jpg
http://lien-hair.jp/wp-content/themes/twentyeleven/languages/msg.jpg
http://go-technical.com/modules/php/msg.jpg
http://titusrealestate.com.fj/.well-known/pki-validation/msg.jpg
http://kapuaskampung.com/templates/protostar/css/msg.jpg
http://darbartech.com/wp-content/themes/shopper/woocommerce/global/msg.jpg
http://hobbysalon-tf.com/js/msg.jpg
http://92.63.197.153/3.exe
http://92.63.197.153/2.exe
http://92.63.197.153/1.exe
http://pange.cz/cesty/2008/indie/classes/msg.jpg
http://hobbysalon-tf.com/js/msg.jpg
http://futureskool.com/wp-content/themes/tunepipe-basic-parent/inc/_notes/msg.jpg
http://proton.pk/wp-content/plugins/acf-cf7/msg.jpg
http://dichvucong.vn/.well-known/acme-challenge/msg.jpg
http://iteeman.com/wp-content/themes/melos/images/slideshow/msg.jpg
http://newmarketing.no/wp-content/themes/pond/includes/msg.jpg
http://contingentsecurity.com/wp-content/themes/expound/inc/msg.jpg
http://darsab.se/wp-content/themes/zerif-lite/languages/msg.jpg
http://3log.sk/templates/rt_replicant2_j15/images/body/style1/msg.jpg
http://webserverthai.com/home/img/msg.jpg
http://sundercats.oksoftware.net/msg.jpg
http://optionscity.com/wp-content/wptouch-data/debug/safebrowsing.exe
http://lingvaworld.ru/media/system/css/messg.jpg
http://3forfree.org/wp-content/themes/twentyseventeen/assets/css/messg.jpg
http://firstbaptisthackensack.org/templates/hexa_corp/cache/messg.jpg
http://caringsoul.org/includes/messg.jpg
http://semiworldwide.net/templates/home/html/_mod_search/messg.jpg
http://strewn.org/reductio/messg.jpg
http://198.98.62.207/ldr.exe
http://monkeyinferno.net/seledka.exe
http://198.98.62.207/seledka.exe
http://monkeyinferno.net/ldr.exe
http://92.63.197.153/4.exe
http://92.63.197.153/3.exe
http://92.63.197.153/1.exe
http://92.63.197.153/work/1.exe
http://mobshop.schmutzki.de/.well-known/acme-challenge/messg.jpg
http://thu-san-world-challenges.org/wp-admin/css/colors/blue/messg.jpg
