name: "CI"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gtrunsec/SOC-action@main
        with:
          run-command: echo hello SOC Action!
          zeek-lint: ./scripts

      - name: Nix Flake show
        run: nix -Lv flake show

      - name: Run nvfetcher
        run: nix -Lv develop -c run-nvfetcher

      - name: Nix Flake lock Update
        run: nix -Lv flake update

      - name: Build hardenedlinux-zeek-scripts
        run: nix -Lv develop -c hardenedlinux-zeek-scripts

      - name: Commit changes
        if: ${{ env.COMMIT_MSG != null }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MSG }}
